name: Hello World
run-name: Print Hello World
on:
  workflow_dispatch:
    inputs:
      Confirm Yes:
        description: 'Type "yes" to confirm'
        required: true
       
jobs:
  name: greetings
    steps:
      - name: Greet
        run: echo "Hello world!"

