name : printing branch name

on: [push]

jobs:
  print_branch_name:
    runs-on: [self-hosted,linux]
    steps:
      - name: Print the branch name
        run: echo "The branch that triggered this workflow is: ${{ github.ref }}"